Private Events / Microverse Association Project
Godswilly/private_events pull request #2
Opened 2020-10-14 14:03 UTC by gurbuzertunga

In this project we;

- Implemented a User, Events and Event Attendees databases and relationship between them,
- Started Using Tailwind CSS as a practice and CSS styling of the project,
- A User can create and join different events,
- An Event can have multiple different attendees and these will show in Event's show page,
- A user can attend to multiple events and these will show in User's show page.

2020-10-14 15:58 UTC, maelfosso requested changes
# changes required :red_circle:

Hello,

Thank you the well done job so far
However, there are some issues to fix 

1. Kindly add **indexes** in `event_attendees` table for the two references

2. Kindly add unit and integrations as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) and [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png)

3- It's possible, in your app, to create an event without being logged in
![Screenshot at 2020-10-14 16:45:21](https://user-images.githubusercontent.com/8848104/96013062-bdcbaa80-0e3c-11eb-8837-8753626536f2.png)
Read the requirement [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png). Kindly fix that, please.
To fix that use `before_action` for all the actions into EventsController

4- If you take a closely look at this screenshot
![Screenshot at 2020-10-14 16:51:39](https://user-images.githubusercontent.com/8848104/96013801-93c6b800-0e3d-11eb-8fdc-0ab2a5fa7700.png)
You will notice that **alice** appears twice in the list of attendees.
Kindly fix that, please.

5- There is the screenshot of users' list
![Screenshot at 2020-10-14 16:52:55](https://user-images.githubusercontent.com/8848104/96013987-c96ba100-0e3d-11eb-86e7-64ef6a1c2082.png)
Kindly improve it because it's difficult to understand. Use a `<table>` for example

6- Read the comments left below

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-10-14 15:58 UTC, maelfosso commented on app/views/layouts/application.html.erb
> +          <% end %>
Kindly remove logic from views. Move them into view helpers.

2020-10-14 15:58 UTC, maelfosso commented on config/routes.rb
> +  resources :events
**`OPTIONAL`**
Routes can be restricted to this `resources :events, only: [:new, :create, :show, :index]`

2020-10-14 15:58 UTC, maelfosso commented on app/views/users/show.html.erb
> +  <% end %>
That block is not really necessary.
You can remove it.

2020-10-15 11:09 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi team! Great job implementing most of the suggested changes in the last review. There are a few issues I'd like you to consider before moving forward though. These include:
- [ ] The `New User` button on your users' page doesn't work as expected. It returns an error. Either fix it or remove it so that the new user can only be created from the `Sign Up` link in the navbar.
- [ ] __[Optional]__ Your authentication system lacks some vital functionality e.g. when an unlogged-in user tries to register for an event, an error is returned. Please fix your authentication so that the user is shown an appropriate message. Probably indicating that one has to be logged in to register for an event. This is the same for the edit action of any event.
- [ ] Add integration tests for authentication (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] Add integration tests event managment features (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)) __[Hint]__ [Here](https://www.codewithjason.com/rails-integration-tests-rspec-capybara/) is a nice article about writing integration tests.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-10-15 13:22 UTC, trekab approved these changes
### Approved! :tada: 
Well done implementing the suggested changes, team! Keep up the good work!

_Happy coding!_
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-10-15 13:40 UTC, merged